# netlify.toml
# Configuration file for Netlify deployment settings

# Build settings
[build]
  publish = "../silassentinel.github.io/"
  command = "npm run build"
  ignore_dot_git = false

# Set proper MIME types for JavaScript files
[[headers]]
  # Define headers for all JavaScript files
  for = "/_astro/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  # Define headers for all JS module files
  for = "/_astro/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Additional headers for other JavaScript file patterns
[[headers]]
  for = "/_astro/*_lang.*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/_astro/*.astro_*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Set cache control for static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set security headers for the entire site
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"